server:
  port: 8081

spring:
  profiles:
    include: prod
  application:
    name: recommendations
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    enabled: true

