server:
  port: 8080

spring:
  profiles:
    include: prod
  application:
    name: recommendations

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    enabled: true


