name: Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      OPEN_AI_URI: ${{ secrets.OPEN_AI_URI }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build --build-arg OPEN_AI_KEY="${{ env.OPEN_AI_KEY }}" \
          --build-arg OPEN_AI_URI="${{ env.OPEN_AI_URI }}
          -t destination-api .
          docker push rat2race/destination-api:${GITHUB_SHA::7}
